module.exports = [
    {
      "city": "Sanaa", 
      "lat": "15.3500", 
      "lng": "44.2000", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Amānat al ‘Āşimah", 
      "capital": "primary", 
      "population": "2957000", 
      "population_proper": "2957000"
    }, 
    {
      "city": "Ta‘izz", 
      "lat": "13.5789", 
      "lng": "44.0219", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "admin", 
      "population": "596672", 
      "population_proper": "596672"
    }, 
    {
      "city": "Al Ḩudaydah", 
      "lat": "14.8022", 
      "lng": "42.9511", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "admin", 
      "population": "548433", 
      "population_proper": "548433"
    }, 
    {
      "city": "Aden", 
      "lat": "12.8000", 
      "lng": "45.0333", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Adan", 
      "capital": "admin", 
      "population": "507355", 
      "population_proper": "507355"
    }, 
    {
      "city": "Ibb", 
      "lat": "13.9759", 
      "lng": "44.1709", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "", 
      "population": "234837", 
      "population_proper": "234837"
    }, 
    {
      "city": "Ibb", 
      "lat": "13.9667", 
      "lng": "44.1667", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "admin", 
      "population": "225611", 
      "population_proper": "225611"
    }, 
    {
      "city": "Dhamār", 
      "lat": "14.5500", 
      "lng": "44.4017", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Dhamār", 
      "capital": "admin", 
      "population": "160114", 
      "population_proper": "160114"
    }, 
    {
      "city": "Al Mukallā", 
      "lat": "14.5333", 
      "lng": "49.1333", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "admin", 
      "population": "144137", 
      "population_proper": "144137"
    }, 
    {
      "city": "Tarīm", 
      "lat": "16.0500", 
      "lng": "49.0000", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "105552", 
      "population_proper": "105552"
    }, 
    {
      "city": "Ash Shaykh ‘Uthmān", 
      "lat": "12.8866", 
      "lng": "45.0279", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Adan", 
      "capital": "minor", 
      "population": "105248", 
      "population_proper": "105248"
    }, 
    {
      "city": "Zinjibār", 
      "lat": "13.1283", 
      "lng": "45.3803", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Abyan", 
      "capital": "admin", 
      "population": "70801", 
      "population_proper": "70801"
    }, 
    {
      "city": "Şa‘dah", 
      "lat": "16.9358", 
      "lng": "43.7644", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şa‘dah", 
      "capital": "admin", 
      "population": "70203", 
      "population_proper": "70203"
    }, 
    {
      "city": "Say’ūn", 
      "lat": "15.9430", 
      "lng": "48.7873", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "68747", 
      "population_proper": "68747"
    }, 
    {
      "city": "Ash Shiḩr", 
      "lat": "14.7608", 
      "lng": "49.6069", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "68313", 
      "population_proper": "68313"
    }, 
    {
      "city": "Zabīd", 
      "lat": "14.2000", 
      "lng": "43.3167", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "50781", 
      "population_proper": "50781"
    }, 
    {
      "city": "Ḩajjah", 
      "lat": "15.6950", 
      "lng": "43.5975", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "admin", 
      "population": "46568", 
      "population_proper": "46568"
    }, 
    {
      "city": "Bājil", 
      "lat": "15.0583", 
      "lng": "43.2850", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "46005", 
      "population_proper": "46005"
    }, 
    {
      "city": "Radā‘", 
      "lat": "14.4295", 
      "lng": "44.8341", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "minor", 
      "population": "45233", 
      "population_proper": "45233"
    }, 
    {
      "city": "Bayt al Faqīh", 
      "lat": "14.5167", 
      "lng": "43.3167", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "41652", 
      "population_proper": "41652"
    }, 
    {
      "city": "Al Qā‘idah", 
      "lat": "13.7569", 
      "lng": "44.1392", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "", 
      "population": "39254", 
      "population_proper": "39254"
    }, 
    {
      "city": "Al Bayḑā’", 
      "lat": "13.9790", 
      "lng": "45.5740", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "admin", 
      "population": "37821", 
      "population_proper": "37821"
    }, 
    {
      "city": "‘Ataq", 
      "lat": "14.5500", 
      "lng": "46.8000", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "admin", 
      "population": "37315", 
      "population_proper": "37315"
    }, 
    {
      "city": "Yarīm", 
      "lat": "14.2978", 
      "lng": "44.3778", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "34805", 
      "population_proper": "34805"
    }, 
    {
      "city": "Laḩij", 
      "lat": "13.0500", 
      "lng": "44.8833", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Laḩij", 
      "capital": "admin", 
      "population": "30661", 
      "population_proper": "30661"
    }, 
    {
      "city": "Ja‘ār", 
      "lat": "13.2167", 
      "lng": "45.3000", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Abyan", 
      "capital": "minor", 
      "population": "29495", 
      "population_proper": "29495"
    }, 
    {
      "city": "Al Ghayz̧ah", 
      "lat": "16.2394", 
      "lng": "52.1638", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Mahrah", 
      "capital": "admin", 
      "population": "27404", 
      "population_proper": "20000"
    }, 
    {
      "city": "Ma‘bar", 
      "lat": "14.7939", 
      "lng": "44.2936", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Dhamār", 
      "capital": "minor", 
      "population": "24707", 
      "population_proper": "24707"
    }, 
    {
      "city": "Ma’rib", 
      "lat": "15.4228", 
      "lng": "45.3375", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ma’rib", 
      "capital": "admin", 
      "population": "16794", 
      "population_proper": "16794"
    }, 
    {
      "city": "Ad Dīs ash Sharqīyah", 
      "lat": "14.8833", 
      "lng": "49.8667", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "16614", 
      "population_proper": "16614"
    }, 
    {
      "city": "Jiblah", 
      "lat": "13.9167", 
      "lng": "44.1500", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "15431", 
      "population_proper": "15431"
    }, 
    {
      "city": "Khamir", 
      "lat": "15.9900", 
      "lng": "43.9500", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "15333", 
      "population_proper": "15333"
    }, 
    {
      "city": "Mocha", 
      "lat": "13.3167", 
      "lng": "43.2500", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "14562", 
      "population_proper": "14562"
    }, 
    {
      "city": "Raydah", 
      "lat": "15.8233", 
      "lng": "44.0386", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "13971", 
      "population_proper": "13971"
    }, 
    {
      "city": "Ḩadībū", 
      "lat": "12.6519", 
      "lng": "54.0239", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Arkhabīl Suquţrá", 
      "capital": "admin", 
      "population": "11396", 
      "population_proper": "8545"
    }, 
    {
      "city": "Al Maḩwīt", 
      "lat": "15.4694", 
      "lng": "43.5453", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Maḩwīt", 
      "capital": "admin", 
      "population": "10593", 
      "population_proper": "10593"
    }, 
    {
      "city": "Ar Rawḑah", 
      "lat": "14.4800", 
      "lng": "47.2700", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "minor", 
      "population": "6649", 
      "population_proper": "6649"
    }, 
    {
      "city": "Ḑawrān ad Daydah", 
      "lat": "14.7608", 
      "lng": "44.1904", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Dhamār", 
      "capital": "minor", 
      "population": "5695", 
      "population_proper": "5695"
    }, 
    {
      "city": "Qalansīyah", 
      "lat": "12.6833", 
      "lng": "53.4833", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Arkhabīl Suquţrá", 
      "capital": "minor", 
      "population": "4741", 
      "population_proper": "4741"
    }, 
    {
      "city": "Markaz Mudhaykirah", 
      "lat": "13.8855", 
      "lng": "43.9672", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "1245", 
      "population_proper": "1245"
    }, 
    {
      "city": "Sayḩūt", 
      "lat": "15.2105", 
      "lng": "51.2454", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Mahrah", 
      "capital": "minor", 
      "population": "189", 
      "population_proper": "189"
    }, 
    {
      "city": "Crater", 
      "lat": "12.7775", 
      "lng": "45.0328", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Adan", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "At Tawāhī", 
      "lat": "12.7847", 
      "lng": "44.9802", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Adan", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Manşūrah", 
      "lat": "12.8602", 
      "lng": "44.9817", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Adan", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Ma‘allā’", 
      "lat": "12.7899", 
      "lng": "45.0024", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Adan", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Masālīyah", 
      "lat": "13.5320", 
      "lng": "43.9956", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "‘Amrān", 
      "lat": "15.6594", 
      "lng": "43.9439", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Jabīn", 
      "lat": "14.7040", 
      "lng": "43.5990", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Raymah", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Aḑ Ḑāli‘", 
      "lat": "13.6957", 
      "lng": "44.7314", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Aḑ Ḑāli‘", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Ḩazm", 
      "lat": "16.1641", 
      "lng": "44.7769", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Jawf", 
      "capital": "admin", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Misrākh", 
      "lat": "13.4606", 
      "lng": "44.0204", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Khawr Maksar", 
      "lat": "12.8123", 
      "lng": "45.0334", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Adan", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Banī an Nahārī", 
      "lat": "15.6398", 
      "lng": "43.5563", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Dhī as Sufāl", 
      "lat": "13.8345", 
      "lng": "44.1147", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Qaryat al Qābil", 
      "lat": "15.4503", 
      "lng": "44.1277", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Amānat al ‘Āşimah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ar Rawḑah", 
      "lat": "15.4325", 
      "lng": "44.2240", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Amānat al ‘Āşimah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩawrah", 
      "lat": "13.3575", 
      "lng": "44.1458", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Khayrān", 
      "lat": "16.0219", 
      "lng": "43.3786", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Banī al ‘Awwām", 
      "lat": "15.5812", 
      "lng": "43.5873", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Maḩābishah", 
      "lat": "15.9476", 
      "lng": "43.4359", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Dār an Nāşir", 
      "lat": "13.5571", 
      "lng": "44.0152", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ar Rubū‘", 
      "lat": "13.7802", 
      "lng": "43.8690", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Sūq Shamar", 
      "lat": "15.8850", 
      "lng": "43.3681", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al ‘Ayn", 
      "lat": "13.3300", 
      "lng": "44.0921", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Makhādir", 
      "lat": "14.1222", 
      "lng": "44.1980", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Aş Şalw", 
      "lat": "13.3289", 
      "lng": "44.2171", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Qaryat ad Da‘īs", 
      "lat": "13.9877", 
      "lng": "44.2749", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "As Sayyānī", 
      "lat": "13.8427", 
      "lng": "44.1739", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Waḑarah", 
      "lat": "15.7107", 
      "lng": "43.4832", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Z̧almah al ‘Ulyā", 
      "lat": "14.1023", 
      "lng": "44.0940", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Miftāḩ", 
      "lat": "15.9743", 
      "lng": "43.4638", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩayfān", 
      "lat": "13.3178", 
      "lng": "44.2801", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Yufrus", 
      "lat": "13.4553", 
      "lng": "43.9470", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al ‘Udayn", 
      "lat": "13.9692", 
      "lng": "43.9967", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ar Rawnah", 
      "lat": "13.7564", 
      "lng": "43.8029", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ash Shaghādirah", 
      "lat": "15.6200", 
      "lng": "43.5206", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "As Sarīr", 
      "lat": "13.7383", 
      "lng": "44.6839", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Aḑ Ḑāli‘", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kusmah", 
      "lat": "14.5817", 
      "lng": "43.6368", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Raymah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Sūq ar Rubū‘", 
      "lat": "14.5115", 
      "lng": "44.0151", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Dhamār", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Nashmah", 
      "lat": "13.3903", 
      "lng": "43.9683", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Washḩah", 
      "lat": "16.3077", 
      "lng": "43.4107", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "As Saddah", 
      "lat": "14.1221", 
      "lng": "44.4214", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ash Shāhil", 
      "lat": "15.8666", 
      "lng": "43.4049", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kuḩlān ‘Affār", 
      "lat": "15.7331", 
      "lng": "43.7190", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bayt ‘Adhāqah", 
      "lat": "15.6158", 
      "lng": "43.7023", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ar Riḑā’ī", 
      "lat": "14.0171", 
      "lng": "44.3941", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Jurbah", 
      "lat": "13.7915", 
      "lng": "45.1589", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Laḩij", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ad Dann", 
      "lat": "14.3518", 
      "lng": "43.8528", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Dhamār", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Raşad", 
      "lat": "13.7122", 
      "lng": "45.3032", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Abyan", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "An Naz̧īr", 
      "lat": "16.9092", 
      "lng": "43.2623", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şa‘dah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Madīnat Lab‘ūs", 
      "lat": "13.8667", 
      "lng": "45.2500", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Laḩij", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Jamīmah", 
      "lat": "16.0179", 
      "lng": "43.5965", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Banī Ḩujjāj", 
      "lat": "15.4168", 
      "lng": "43.3193", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Maḩwīt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Mirwāḩ", 
      "lat": "15.4722", 
      "lng": "43.4294", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Maḩwīt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩazm al ‘Udayn", 
      "lat": "14.0274", 
      "lng": "44.0053", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ar Raḑmah", 
      "lat": "14.2197", 
      "lng": "44.5866", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Aş Şafaqayn", 
      "lat": "15.3792", 
      "lng": "43.4205", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Maḩwīt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Mabyan", 
      "lat": "15.7377", 
      "lng": "43.5570", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "An Nādirah", 
      "lat": "14.0963", 
      "lng": "44.4756", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Shahārat al Ghīs", 
      "lat": "16.1845", 
      "lng": "43.7027", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Madān", 
      "lat": "16.2241", 
      "lng": "43.6438", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "At Turbah", 
      "lat": "13.2127", 
      "lng": "44.1241", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Aţ Ţawīlah", 
      "lat": "15.4939", 
      "lng": "43.7478", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Maḩwīt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Şuwayr", 
      "lat": "16.1818", 
      "lng": "43.6099", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ad Dimnah", 
      "lat": "13.4540", 
      "lng": "44.1817", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ar Ramādī", 
      "lat": "13.9564", 
      "lng": "43.7846", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Banī Bakr", 
      "lat": "13.9333", 
      "lng": "45.2667", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Laḩij", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩabābah", 
      "lat": "15.5442", 
      "lng": "43.8756", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Shibām", 
      "lat": "15.5094", 
      "lng": "43.9045", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Maḩwīt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Mighlāf", 
      "lat": "15.2877", 
      "lng": "43.1891", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Manşūrīyah", 
      "lat": "14.6856", 
      "lng": "43.2992", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Ḩadīyah", 
      "lat": "14.5264", 
      "lng": "43.5704", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Raymah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Saḩḩab", 
      "lat": "15.6022", 
      "lng": "44.0242", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Maghrabah", 
      "lat": "15.8772", 
      "lng": "43.6667", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ar Rujum", 
      "lat": "15.4578", 
      "lng": "43.6323", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Maḩwīt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Aḑ Ḑaḩī", 
      "lat": "15.2152", 
      "lng": "43.0702", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Riḩāb", 
      "lat": "14.2276", 
      "lng": "44.1881", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kushar", 
      "lat": "16.1552", 
      "lng": "43.4210", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Z̧abah", 
      "lat": "14.4905", 
      "lng": "44.1311", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Dhamār", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Ḩusayn", 
      "lat": "13.7920", 
      "lng": "44.7689", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Aḑ Ḑāli‘", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Sharas", 
      "lat": "15.7123", 
      "lng": "43.6493", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Najd al Jamā‘ī", 
      "lat": "13.9158", 
      "lng": "44.3245", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ibb", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩabūr", 
      "lat": "16.0510", 
      "lng": "43.7070", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bayt as Sayyid", 
      "lat": "15.5045", 
      "lng": "44.4150", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şan‘ā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Matwaḩ", 
      "lat": "15.0676", 
      "lng": "43.6421", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şan‘ā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Aslam", 
      "lat": "16.0596", 
      "lng": "43.3275", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Az Zaydīyah", 
      "lat": "15.3305", 
      "lng": "43.0063", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Aḑ Ḑil‘", 
      "lat": "14.6720", 
      "lng": "43.8183", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Raymah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Qanāwiş", 
      "lat": "15.4929", 
      "lng": "43.1343", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Riqāb", 
      "lat": "14.8860", 
      "lng": "43.4649", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "As Sūdah", 
      "lat": "15.9586", 
      "lng": "43.7808", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Māwiyah", 
      "lat": "13.5829", 
      "lng": "44.3477", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Az Zuhrah", 
      "lat": "15.7238", 
      "lng": "42.9958", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al ‘Urrah", 
      "lat": "15.2467", 
      "lng": "43.8883", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şan‘ā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Aḩad", 
      "lat": "14.2583", 
      "lng": "43.6417", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Dhamār", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Aş Şarārah", 
      "lat": "15.7945", 
      "lng": "43.8700", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Marāwi‘ah", 
      "lat": "14.8307", 
      "lng": "43.1539", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Az Zāhir", 
      "lat": "16.3173", 
      "lng": "44.4951", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Jawf", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩays", 
      "lat": "13.9317", 
      "lng": "43.4831", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "As Sūq al Jadīd", 
      "lat": "15.8250", 
      "lng": "44.0620", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Milāḩ", 
      "lat": "14.4162", 
      "lng": "44.7862", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Mashāf", 
      "lat": "16.8584", 
      "lng": "43.1978", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şa‘dah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "As Suwaydā", 
      "lat": "13.7869", 
      "lng": "45.2304", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Laḩij", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "An Nāşirah", 
      "lat": "15.7728", 
      "lng": "43.8090", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Khirāb", 
      "lat": "16.5544", 
      "lng": "44.2905", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Jawf", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "As Sukhnah", 
      "lat": "14.7941", 
      "lng": "43.4362", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩammām Damt", 
      "lat": "14.0903", 
      "lng": "44.6701", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Aḑ Ḑāli‘", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ku‘aydinah", 
      "lat": "15.8210", 
      "lng": "43.3372", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Maqbanah", 
      "lat": "13.6639", 
      "lng": "43.6873", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Jarrāḩī", 
      "lat": "14.1325", 
      "lng": "43.3885", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Dhī Nā‘im", 
      "lat": "14.1057", 
      "lng": "45.4481", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Mustabā’", 
      "lat": "16.2282", 
      "lng": "43.2490", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Khāniq", 
      "lat": "15.5025", 
      "lng": "44.1816", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şan‘ā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ar Rawḑ", 
      "lat": "16.0614", 
      "lng": "44.8101", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Jawf", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Az Zāhir", 
      "lat": "13.9667", 
      "lng": "45.4833", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩadādah", 
      "lat": "13.1754", 
      "lng": "44.2746", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Laḩij", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Jum‘ah", 
      "lat": "14.7378", 
      "lng": "43.9649", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Dhamār", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩammām ‘Alī", 
      "lat": "14.6637", 
      "lng": "44.1476", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Dhamār", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Sayyān", 
      "lat": "15.1718", 
      "lng": "44.3244", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şan‘ā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ghaymān", 
      "lat": "15.2725", 
      "lng": "44.3540", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şan‘ā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Qa‘ţabah", 
      "lat": "13.8549", 
      "lng": "44.7058", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Aḑ Ḑāli‘", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḑawrān", 
      "lat": "13.7744", 
      "lng": "44.4420", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Aḑ Ḑāli‘", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Zakhim", 
      "lat": "14.2950", 
      "lng": "44.6850", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Burayqah", 
      "lat": "12.7394", 
      "lng": "44.8842", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Adan", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al ‘Aqabah", 
      "lat": "14.2718", 
      "lng": "44.7870", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al ‘Awābil", 
      "lat": "13.8375", 
      "lng": "44.8643", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Aḑ Ḑāli‘", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Hijrah", 
      "lat": "17.2979", 
      "lng": "43.3872", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şa‘dah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Sūq al Khamīs", 
      "lat": "17.1813", 
      "lng": "43.2881", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şa‘dah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Malāḩīţ", 
      "lat": "16.7685", 
      "lng": "43.2758", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şa‘dah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Kharāb", 
      "lat": "16.9913", 
      "lng": "43.3389", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şa‘dah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Manākhah", 
      "lat": "15.0742", 
      "lng": "43.7416", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şan‘ā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Markaz al Marīr", 
      "lat": "13.9818", 
      "lng": "43.5955", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Khamīs", 
      "lat": "15.1853", 
      "lng": "43.5112", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Maḩwīt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩaydān", 
      "lat": "16.7790", 
      "lng": "43.4337", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şa‘dah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Dhī Jalāl", 
      "lat": "13.6238", 
      "lng": "44.7075", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Aḑ Ḑāli‘", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bidbadah", 
      "lat": "15.4250", 
      "lng": "44.7000", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ma’rib", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩabīl ar Raydah", 
      "lat": "13.6444", 
      "lng": "44.8510", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Laḩij", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Mayfa’ah", 
      "lat": "14.4639", 
      "lng": "44.5487", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Dhamār", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Sāqayn", 
      "lat": "16.8770", 
      "lng": "43.5250", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şa‘dah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩaraḑ", 
      "lat": "16.4097", 
      "lng": "43.0588", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "‘Ubāl", 
      "lat": "14.9881", 
      "lng": "43.5444", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Jiḩānah", 
      "lat": "15.2263", 
      "lng": "44.4824", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şan‘ā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kirsh", 
      "lat": "13.3647", 
      "lng": "44.4905", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Laḩij", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Dhaybīn", 
      "lat": "15.9771", 
      "lng": "44.1292", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Matnah", 
      "lat": "15.2533", 
      "lng": "44.0247", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şan‘ā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Zarājah", 
      "lat": "14.8669", 
      "lng": "44.3787", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Dhamār", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "‘Abs", 
      "lat": "16.0029", 
      "lng": "43.1972", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Mafḩaq", 
      "lat": "15.1016", 
      "lng": "43.9030", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şan‘ā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "At Tuḩaytā’", 
      "lat": "14.1836", 
      "lng": "43.2264", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Luḩayyah", 
      "lat": "15.7031", 
      "lng": "42.6909", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ad Durayhimī", 
      "lat": "14.6370", 
      "lng": "43.0550", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Wa‘lān", 
      "lat": "15.0702", 
      "lng": "44.2764", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şan‘ā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Markaz Bilād aţ Ţa‘ām", 
      "lat": "14.8336", 
      "lng": "43.5364", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Raymah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Qaflah", 
      "lat": "16.3190", 
      "lng": "43.7679", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Majz", 
      "lat": "17.0694", 
      "lng": "43.5751", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şa‘dah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "An Najd", 
      "lat": "14.4215", 
      "lng": "45.2960", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Rajūzah", 
      "lat": "16.7006", 
      "lng": "44.4145", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Jawf", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Ḩabīlayn", 
      "lat": "13.5200", 
      "lng": "44.8508", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Laḩij", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Ḩayfah", 
      "lat": "15.7349", 
      "lng": "44.2379", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şan‘ā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bayt Marrān", 
      "lat": "15.6931", 
      "lng": "44.2053", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şan‘ā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Ghayl", 
      "lat": "16.1077", 
      "lng": "44.6800", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Jawf", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al ‘Ashshah", 
      "lat": "16.2565", 
      "lng": "43.8548", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Matūn", 
      "lat": "16.2306", 
      "lng": "44.5848", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Jawf", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩabīl al Jabr", 
      "lat": "13.6042", 
      "lng": "44.9858", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Laḩij", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bayḩān", 
      "lat": "14.8007", 
      "lng": "45.7189", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ash Shuqayrah", 
      "lat": "13.1345", 
      "lng": "43.7864", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Khawkhah", 
      "lat": "13.8071", 
      "lng": "43.2493", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩūth", 
      "lat": "16.2311", 
      "lng": "43.9685", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "As Sawādīyah", 
      "lat": "14.3011", 
      "lng": "45.2215", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Munīrah", 
      "lat": "15.3225", 
      "lng": "42.9300", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Mukayrās", 
      "lat": "13.9443", 
      "lng": "45.6707", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Mawza‘", 
      "lat": "13.2683", 
      "lng": "43.5099", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Musaymīr", 
      "lat": "13.4439", 
      "lng": "44.6153", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Laḩij", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Ḩarjah", 
      "lat": "15.4887", 
      "lng": "44.6657", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ma’rib", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Sūq Sibāḩ", 
      "lat": "13.8144", 
      "lng": "45.3923", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Abyan", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Aş Şawma‘ah", 
      "lat": "14.0851", 
      "lng": "45.8010", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Suḩayl Shibām", 
      "lat": "15.9145", 
      "lng": "48.6386", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Lawdar", 
      "lat": "13.8828", 
      "lng": "45.8686", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Abyan", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Aş Şa‘īd", 
      "lat": "14.3301", 
      "lng": "46.8729", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Qurayshīyah", 
      "lat": "14.5122", 
      "lng": "44.8536", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩişn Banī Sa‘d", 
      "lat": "16.2729", 
      "lng": "44.4773", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Jawf", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩarīb", 
      "lat": "14.9316", 
      "lng": "45.5036", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ma’rib", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Ḩumaydāt", 
      "lat": "16.4844", 
      "lng": "44.4293", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Jawf", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al ‘Āqir", 
      "lat": "14.5682", 
      "lng": "45.9116", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Aş Şalīf", 
      "lat": "15.3076", 
      "lng": "42.6711", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Ghaylah", 
      "lat": "14.5958", 
      "lng": "45.5833", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Wuday‘", 
      "lat": "13.7721", 
      "lng": "46.0179", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Abyan", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al ‘Inān", 
      "lat": "16.7219", 
      "lng": "44.3125", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Jawf", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Juban", 
      "lat": "14.0116", 
      "lng": "44.8746", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Aḑ Ḑāli‘", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Ḩazm", 
      "lat": "14.6892", 
      "lng": "45.6096", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ash Sharyah", 
      "lat": "14.3566", 
      "lng": "45.0224", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ţawr al Bāḩah", 
      "lat": "13.1818", 
      "lng": "44.2997", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Laḩij", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Ḩashwah", 
      "lat": "16.9064", 
      "lng": "44.2762", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şa‘dah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Mūdīyah", 
      "lat": "13.9284", 
      "lng": "46.0825", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Abyan", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ash Shawātī", 
      "lat": "16.7831", 
      "lng": "43.8126", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şa‘dah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩabbān", 
      "lat": "14.3541", 
      "lng": "47.0765", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Āl Ma‘ūdah", 
      "lat": "14.2106", 
      "lng": "45.3873", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Ḩajab", 
      "lat": "14.8519", 
      "lng": "45.5290", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Maşlūb", 
      "lat": "16.1827", 
      "lng": "44.6261", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Jawf", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Mīdī", 
      "lat": "16.3210", 
      "lng": "42.8130", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩajjah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Madīd", 
      "lat": "15.6445", 
      "lng": "44.4734", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şan‘ā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ghayl Bā Wazīr", 
      "lat": "14.7761", 
      "lng": "49.3661", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Qaţan", 
      "lat": "15.8406", 
      "lng": "48.4556", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Marbāţ", 
      "lat": "14.2057", 
      "lng": "46.3881", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Aqţa‘", 
      "lat": "14.6622", 
      "lng": "45.3512", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ma’rib", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kamarān", 
      "lat": "15.3351", 
      "lng": "42.6096", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Ḩudaydah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Judaydah", 
      "lat": "15.0751", 
      "lng": "45.2996", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ma’rib", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bāqim as Sūq", 
      "lat": "17.3971", 
      "lng": "43.4774", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şa‘dah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Milāḩ", 
      "lat": "13.4261", 
      "lng": "44.8256", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Laḩij", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Jayshān", 
      "lat": "14.2520", 
      "lng": "46.1791", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Abyan", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Sirār", 
      "lat": "13.6378", 
      "lng": "45.3137", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Abyan", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩurayḑah", 
      "lat": "15.5986", 
      "lng": "48.1828", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "‘Amd", 
      "lat": "15.3000", 
      "lng": "47.9833", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Nişāb", 
      "lat": "14.5074", 
      "lng": "46.4935", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Madghil", 
      "lat": "15.5986", 
      "lng": "45.0401", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ma’rib", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Ḩarf", 
      "lat": "16.3639", 
      "lng": "44.0942", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "‘Amrān", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Mayfa‘ah", 
      "lat": "14.2753", 
      "lng": "47.5841", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Sūq Şirwāḩ", 
      "lat": "15.4493", 
      "lng": "45.0189", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ma’rib", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al ‘Amūd", 
      "lat": "14.7210", 
      "lng": "45.2068", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ma’rib", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ar Raydah", 
      "lat": "15.0350", 
      "lng": "50.4792", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Bāţinah", 
      "lat": "15.4833", 
      "lng": "48.4333", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ash Shaţţ", 
      "lat": "12.8936", 
      "lng": "44.0357", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Laḩij", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Şīf", 
      "lat": "15.3139", 
      "lng": "48.3300", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Şanā’", 
      "lat": "15.4000", 
      "lng": "47.7667", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Dhubāb", 
      "lat": "12.9431", 
      "lng": "43.4102", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ta‘izz", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Khawrah", 
      "lat": "14.4320", 
      "lng": "46.1544", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "‘Usaylān", 
      "lat": "15.0320", 
      "lng": "45.8283", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Ḩuşūn", 
      "lat": "15.4739", 
      "lng": "45.3669", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ma’rib", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Maḩfid", 
      "lat": "14.0585", 
      "lng": "46.9133", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Abyan", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Raḩabah", 
      "lat": "14.8953", 
      "lng": "44.9889", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ma’rib", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Sāh", 
      "lat": "15.5772", 
      "lng": "48.8506", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Maswarah", 
      "lat": "14.3440", 
      "lng": "45.7262", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Bayḑā’", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Majzar", 
      "lat": "15.8500", 
      "lng": "44.7750", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ma’rib", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Kitāf", 
      "lat": "17.0317", 
      "lng": "44.1090", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Şa‘dah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Jawl", 
      "lat": "14.4562", 
      "lng": "48.2807", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Asdās", 
      "lat": "15.7660", 
      "lng": "45.0815", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ma’rib", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Maţarah", 
      "lat": "15.5259", 
      "lng": "47.6334", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Az̧ Z̧alī‘ah", 
      "lat": "15.0167", 
      "lng": "48.0167", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Burūm", 
      "lat": "14.3636", 
      "lng": "48.9797", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Aḩwar", 
      "lat": "13.5202", 
      "lng": "46.7137", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Abyan", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩaşwayn", 
      "lat": "15.5905", 
      "lng": "52.1008", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Mahrah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al ‘Ulayb", 
      "lat": "15.1475", 
      "lng": "49.0732", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Shirūj", 
      "lat": "14.6853", 
      "lng": "47.7693", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ruḑūm", 
      "lat": "14.0851", 
      "lng": "47.7431", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Aţ Ţalḩ", 
      "lat": "15.1560", 
      "lng": "47.3990", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩawf", 
      "lat": "16.6338", 
      "lng": "53.0337", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Mahrah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Qishn", 
      "lat": "15.4241", 
      "lng": "51.6784", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Mahrah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Māfūd", 
      "lat": "15.3426", 
      "lng": "47.2522", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Jawl al Majma‘", 
      "lat": "14.9328", 
      "lng": "47.0276", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Shabwah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Maḩjal", 
      "lat": "16.7117", 
      "lng": "44.8477", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Jawf", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Daḩasuways", 
      "lat": "15.7239", 
      "lng": "50.7294", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Mahrah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Bilād", 
      "lat": "16.1381", 
      "lng": "49.2917", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Ḩajar al Mashā’ikh", 
      "lat": "16.1395", 
      "lng": "47.8323", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al ‘Abr", 
      "lat": "16.1333", 
      "lng": "47.2333", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Shiḩan as Suflá", 
      "lat": "17.7700", 
      "lng": "52.4893", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Mahrah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Al Qurḩ", 
      "lat": "16.7333", 
      "lng": "51.4833", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Mahrah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Thamūd", 
      "lat": "17.2924", 
      "lng": "49.9195", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Rumāh", 
      "lat": "17.4553", 
      "lng": "50.5779", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Bi’r Ḩāt", 
      "lat": "17.3220", 
      "lng": "52.0957", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Al Mahrah", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "As Salāsil", 
      "lat": "16.4796", 
      "lng": "48.8315", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }, 
    {
      "city": "Minwakh", 
      "lat": "16.8004", 
      "lng": "48.1085", 
      "country": "Yemen", 
      "iso2": "YE", 
      "admin_name": "Ḩaḑramawt", 
      "capital": "minor", 
      "population": "", 
      "population_proper": ""
    }
  ];